name: Mac2023_CI

on: [push]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v1

    - name: run_all_tests
      env:
        MYAPP_TEMPLATE_QT6: 1
        MYAPP_TEMPLATE_PREFER_QMAKE: 1
      run: ./run_all_tests.sh
