#!/bin/bash

set -Eeuxo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

CUR_GIT_ROOT=$(git rev-parse --show-toplevel)

# set qt5 path to the submodule contents
PATH="$CUR_GIT_ROOT/build_qt_binaries/qt5_opt_install/bin:$PATH"
# comment out next line if you wish to prefer 'opt' in place of 'dbg':
PATH="$CUR_GIT_ROOT/build_qt_binaries/qt5_dbg_install/bin:$PATH"

# In order that all the qml 'import' statements for our supporting libraries can
# successfully load, you must feed some additional paths to qmlscene like so:

qmlscene -I ../../libstyles/imports/ "$@"
