#!/bin/bash

set -Eeuxo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

CUR_GIT_ROOT=$(git rev-parse --show-toplevel)

TOP_BUILD_FOLDER=build

if [[ -n ${1-} ]]; # the presence of ANY arg is taken to be the TOP_BUILD_FOLDER
then
  TOP_BUILD_FOLDER=${1}
fi

mkdir -p $CUR_GIT_ROOT/${TOP_BUILD_FOLDER}/generated_files/autogenerated
$CUR_GIT_ROOT/tools/update_version_strings.sh $CUR_GIT_ROOT/src/version.genfiles.input/version.h $CUR_GIT_ROOT/${TOP_BUILD_FOLDER}/generated_files/autogenerated/version.h
