#
# Copyright (c) 2020, 219 Design, LLC
# See LICENSE.txt
#
# https://www.219design.com
# Software | Electrical | Mechanical | Product Design
#
name: CMake_Linux_CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    # Remove apt repos that are known to break from time to time
    # See https://github.com/actions/virtual-environments/issues/323
    - name: Remove broken apt repos
      run: |
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

    - if: runner.os == 'Linux'
      # Fix (another kind) of azure ubuntu apt repo issue. (Unable to connect to azure.archive.ubuntu.com)
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list

    - name: run_all_tests_clang
      env:
        MYAPP_TEMPLATE_COMPILERCHOICE_CLANG: 1
      run: ./run_all_tests.sh

    - name: run_all_tests_qt6_android
      env:
        MYAPP_TEMPLATE_BUILD_ANDROID: 1
        MYAPP_TEMPLATE_QT6: 1
      run: ./run_all_tests.sh

    # If we were to enable AppImage tests, then this one must go last.
    - name: run_all_tests_gcc
      env:
        # Note: AppImage test (not used here) does destructive actions and can break further tests.
        NOTYET_MYAPP_TEMPLATE_BUILD_APPIMAGE: 1
      run: ./run_all_tests.sh
