name: Mac_CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: run_all_tests
      env:
        MYAPP_TEMPLATE_SKIP_ANDROID: 1
        MYAPP_TEMPLATE_SKIP_APPIMAGE: 1
      run: ./run_all_tests.sh
