#
# Copyright (c) 2020, 219 Design, LLC
# See LICENSE.txt
#
# https://www.219design.com
# Software | Electrical | Mechanical | Product Design
#
name: Linux_CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1

    - name: compute nameid for this run
      env:
        nameidinput: "${{ github.head_ref || github.ref_name }}"
      run: |
        echo "our_nameid=${nameidinput//\//-}" >> $GITHUB_ENV

    # Remove apt repos that are known to break from time to time
    # See https://github.com/actions/virtual-environments/issues/323
    - name: Remove broken apt repos
      run: |
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

    - if: runner.os == 'Linux'
      # Fix (another kind) of azure ubuntu apt repo issue. (Unable to connect to azure.archive.ubuntu.com)
      run: sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list

    # If we were to enable AppImage tests, then this one must go last.
    - name: run_all_tests_gcc
      env:
        # Note: AppImage test (not used here) does destructive actions and can break further tests.
        NOTYET_MYAPP_TEMPLATE_BUILD_APPIMAGE: 1
        # For a clang (not gcc) qt6 build, see: cmakebuild_linux.yml
      run: ./run_all_tests.sh

    - name: upload_gcc_coverage_reports
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.our_nameid }}.gcc.qt6.coverage_reports"
        path: coverage_reports/
        if-no-files-found: error
        retention-days: 7
        overwrite: false

    # This one must go last, because it does the AppImage tests.
    - name: run_all_tests_gcc_qt5
      env:
        # Nice-to-have: update our AppImage scripts for Qt6.
        # MYAPP_TEMPLATE_BUILD_ANDROID: 1 # <--- see cmakebuild_linux.yml for android
        # Note that AppImage test does destructive actions and can break further tests.
        MYAPP_TEMPLATE_BUILD_APPIMAGE: 1
        MYAPP_TEMPLATE_PREFER_QMAKE: 1
        MYAPP_TEMPLATE_QT5: 1
      run: ./run_all_tests.sh
